version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker/develop/nginx
    ports:
    - 8080:8080
    - 8081:8081
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker/develop/nginx
    volumes:
    - ./frontend:/app

  api:
    build:
      context: api/docker/develop/nginx
    volumes:
    - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker/develop/php-fpm
    volumes:
    - ./api:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: "serverName=ApiAuction"
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: auction

  api-php-cli:
    build:
      context: api/docker/develop/php-cli
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: auction
    volumes:
    - ./api:/app

  api-postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auction
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  api-postgres: